#----------------------------PACKAGES--------------------------------#

loadpackages <- function() {
  if (!require("skimr")) install.packages("skimr"); require("skimr")
  if (!require("purr")) install.packages("purr"); require("purr")
  if (!require("extrafont")) install.packages("extrafont"); require("extrafont")
  if (!require("readr")) install.packages("readr"); require("readr")
  if (!require("tidyverse")) install.packages("tidyverse"); require("tidyverse")
  if (!require("dplyr")) install.packages("dplyr"); require("dplyr")
  if (!require("lubridate")) install.packages("lubridate"); require("lubridate")
  if (!require("data.table")) install.packages("data.table"); require("data.table")
  if (!require("ggplot2")) install.packages("ggplot2"); require("ggplot2")
  if (!require("ggforce")) install.packages("ggforce"); require("ggforce")
  if (!require("grid")) install.packages("grid"); require("grid")
  if (!require("gridExtra")) install.packages("gridExtra"); require("gridExtra")
  if (!require("splitstackshape")) install.packages("splitstackshape"); require("splitstackshape")
  if (!require("knitr")) install.packages("knitr"); require("knitr")
  #if (!require("flextable")) install.packages("flextable"); require("flextable")
  if (!require("officer")) install.packages("officer"); require("officer")
  if (!require("patchwork")) install.packages("patchwork"); require("patchwork")
  if (!require("reshape2")) install.packages("reshape2"); require("reshape2")
  if (!require("jsonlite")) install.packages("jsonlite"); require("jsonlite")
  if (!require("sjPlot")) install.packages("sjPlot"); require("sjPlot")
  if (!require("tidyr")) install.packages("tidyr"); require("tidyr")
  if (!require("dotwhisker")) install.packages("dotwhisker"); require("dotwhisker")
  if (!require("labelled")) install.packages("labelled"); require("labelled")
  if (!require("conflicted")) install.packages("conflicted"); require("conflicted")
  if (!require("gtsummary")) install.packages("gtsummary"); require("gtsummary")
  if (!require("broom")) install.packages("broom"); require("broom")
  if (!require("alpha.correction.bh")) install.packages("alpha.correction.bh"); require("alpha.correction.bh") 
  if (!require("gtExtras")) install.packages("gtExtras"); require("gtExtras")
  if (!require("vtable")) install.packages("vtable"); require("vtable")
  if (!require("rstatix")) install.packages("rstatix"); require("rstatix")
  if (!require("performance")) install.packages("performance"); require("performance")
  if (!require("interactions")) install.packages("interactions"); require("interactions")
  if (!require("jtools")) install.packages("jtools"); require("jtools")
  if (!require("jtools")) install.packages("jtools"); require("jtools")
  if (!require("ggcorrplot")) install.packages("ggcorrplot"); require("ggcorrplot")
  if (!require("patchwork")) install.packages("patchwork"); require("patchwork")
  if (!require("gglm")) install.packages("gglm"); require("gglm")
  if (!require("Rmisc")) install.packages("Rmisc"); require("Rmisc")
  if (!require("lme4")) install.packages("lme4"); require("lme4")
  
}


